web_extra_exposed_ports:
    - name: astro
      container_port: 4321
      http_port: 80
      https_port: 443

web_extra_daemons:
    - name: "astro"
      command: "npm run dev -- --host 0.0.0.0 --port 4321"
      directory: /var/www/html

hooks:
    post-start:
        - exec: "npm install"
